name: Verify

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Install Werf
        uses: werf/trdl/actions/setup-app@2504624ea2798a206c277e8ebf250b495e3bab68 # v0.13.0
        with:
          preset: werf
          group: "2"
          channel: stable
          force: false

      - name: Render Helm chart
        run: werf helm template werf-demo .helm --namespace werf-demo-development

      - name: Build the Werf image
        run: werf build --dev
